GPT_API_URL = 'https://api.openai.com/v1/chat/completions'
GPT_API_KEY = ''
OLLAMA_API_URL = 'http://localhost:11434/api/generate'
COHERE_API_URL = 'https://api.cohere.ai/v1/generate'
COHERE_API_KEY = ''
COHERE_MODEL = 'command-r-plus'
CHROME_DRIVER_PATH = 'chromedriver\\chromedriver.exe'
OUTPUT_FILE_PATH = 'model_output_file_no_link.txt'
SEARCH_ENGINES = {'Google': 'https://www.google.com/search?q=', 'Bing': 'https://www.bing.com/search?q=', 'DuckDuckGo': 'https://duckduckgo.com/?q=', 'Yahoo': 'https://search.yahoo.com/search?p='}
GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent'
GEMINI_API_KEY = ''
